services:
  app:
    build: .
    volumes:
      - ./felicitySolarToken.json:/usr/src/app/felicitySolarToken.json
    ports:
      - "3100:3000"
    environment:
      FELICITY_USERNAME: ${FELICITY_USERNAME}
      FELICITY_PASSWORD: ${FELICITY_PASSWORD}
